version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: adonaiburguer-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: adonaiburguer
      POSTGRES_USER: adonai
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - adonaiburguer_data:/var/lib/postgresql/data

volumes:
  adonaiburguer_data:
